
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://codeberg.org/swsnr/rust-supply-chain/raw/branch/main/audits.toml"

[policy.turnon]
criteria = "safe-to-run"

[[exemptions.cairo-rs]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.cairo-sys-rs]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-run"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gdk4]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gdk4-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gio-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gio-unix]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gio-unix-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.glib-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gobject-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.graphene-rs]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.graphene-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gsk4]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gsk4-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gtk4-macros]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gtk4-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.1"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.13.0"
criteria = "safe-to-run"

[[exemptions.pango]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.pango-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.114"
criteria = "safe-to-run"

[[exemptions.toml_parser]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.7.14"
criteria = "safe-to-run"

[[exemptions.zmij]]
version = "1.0.16"
criteria = "safe-to-run"
