
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://raw.githubusercontent.com/swsnr/rust-supply-chain/refs/heads/main/audits.toml"

[policy.turnon]
criteria = "safe-to-run"

[[exemptions.async-channel]]
version = "2.3.1"
criteria = "safe-to-run"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-run"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.system-deps]]
version = "7.0.2"
criteria = "safe-to-run"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-run"
